[package]
name = "dark-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
futures-util = "0.3.30"
tokio = { version = "1.38.0", features = ["full"] }
zbus = { version = "4.3.1", default-features = false, features = ["tokio"] }
