name: Tests

on:
  pull_request:
  push:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rust toolchain
        run: rustup default nightly

      - name: Build project
        run: cargo build

  check:
    name: Check project

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rust toolchain
        run: rustup default nightly

      - name: Check project
        run: cargo check

  check-format:
    name: Check formatting

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rust toolchain
        run: |
          rustup default nightly
          rustup component add rustfmt

      - name: Check formatting
        run: cargo fmt --check

  nix-build:
    name: Build nix flake

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27

      - name: Check flake
        run: nix flake check

      - name: Build with nix
        run: nix build
